<?php
use Del\Icon;

if ($this->isPossibleOnepageCheckout()) { ?>
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="btn btn-lg btn-primary btn-proceed-checkout btn-checkout pull-right <?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
        <?= Icon::SHOPPING_CART; ?> <span><span><?php echo $this->__('Proceed to Checkout') ?></span></span>
    </button>
    <br class="clear"/>
<?php }
