<?php

$collection = $this->getLoadedProductCollection();
$helper = $this->helper('catalog/output');

if (!$collection->count()){ ?>
    <p class="note-msg"><?= $this->__('There are no products matching the selection.') ?></p>
<?php } else { ?>
    <div class="category-products">
        <?php

        $count = $collection->count() ;
        $columns = $this->getColumnCount();
        $i = 0;

        foreach ($collection as $_product) {
            if ($i++ % $columns == 0) { ?>
                <ul class="products-grid row">
            <?php } ?>
            <li class="item<?php if (($i - 1) % $columns == 0) { ?>first<?php } elseif ($i % $columns == 0) { ?> last<?php } ?> col-md-4">

                <a href="<?= $_product->getProductUrl() ?>"
                   title="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image">
                    <img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize(250, 310); ?>"
                         alt="<?= $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                         class="img-responsive img-thumbnail"/>
                </a>

                <h3 class="panel-title product-name">
                    <a href="<?= $_product->getProductUrl() ?>"
                       title="<?= $this->stripTags($_product->getName(), null, true); ?>">
                        <?= $helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h3>

                <div class="pull-left"> <?= $this->getPriceHtml($_product, true) ?> </div>

                <div class="pull-right">
                    <?php if ($_product->isSaleable()) { ?>
                        <button type="button" title="<?= $this->__('Add to Cart') ?>"
                                class="btn btn-warning btn-cart"
                                onclick="setLocation('<?= $this->getAddToCartUrl($_product) ?>')">
                            <?= $this->__('Add to Cart') ?>
                        </button>
                    <?php } else { ?>
                        <p class="btn btn-alert availability out-of-stock"><span><?= $this->__('Out of stock'); ?></span></p>
                    <?php } ?>
                </div>

            </li>
            <?php if ($i == 6) {break;}
            if ($i % $columns == 0 || $i == $count){?> </ul> <?php } ?>
        <?php } ?>
    </div>
<?php }