
<div class="cart">
    <div class="page-title title-buttons">
        <?php if(!$this->hasError()){ ?>
            <div class="checkout-types pull-right">
                <?php foreach ($this->getMethods('top_methods') as $method) { ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)){ ?>
                        <li><?= $methodHtml; ?></li>
                    <?php } ?>
                <?php } ?>
            </div>
        <?php } ?>
        <h1><?= $this->__('Shopping Cart') ?></h1>
    </div>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?= $this->getChildHtml('form_before') ?>
    <form action="<?= $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?= $this->getBlockHtml('formkey'); ?>
        <fieldset class="clear">
            <table id="shopping-cart-table" class="data-table cart-table table table-condensed table-striped table-hover pc100">
                <col width="1" />
                <col />
                <col width="1" />
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                <col width="1" />
            <?php endif ?>
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th rowspan="<?= $mergedCells; ?>">&nbsp;</th>
                        <th rowspan="<?= $mergedCells; ?>"><span class="nobr"><?= $this->__('Product Name') ?></span></th>
                        <th rowspan="<?= $mergedCells; ?>"></th>
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?= $mergedCells; ?>" class="a-center"><span class="nobr"><?= $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>
                        <th class="a-center" colspan="<?= $mergedCells; ?>"><span class="nobr"><?= $this->__('Unit Price') ?></span></th>
                        <th rowspan="<?= $mergedCells; ?>" class="a-center"><?= $this->__('Qty') ?></th>
                        <th class="a-center" colspan="<?= $mergedCells; ?>"><?= $this->__('Subtotal') ?></th>
                        <th rowspan="<?= $mergedCells; ?>" class="a-center">&nbsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?= $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?= $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?= $this->__('Continue Shopping') ?>" class="button btn-continue  btn btn-sm btn-primary" onclick="setLocation('<?= $this->getContinueShoppingUrl() ?>')"><span><span><?= $this->__('Continue Shopping') ?></span></span></button>
                            <?php endif; ?>
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?= $this->__('Update Shopping Cart'); ?>" class="button btn-update btn btn-sm btn-success"><span><span><?= $this->__('Update Shopping Cart'); ?></span></span></button>
                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?= $this->__('Clear Shopping Cart'); ?>" class="button btn-empty btn btn-sm btn-danger" id="empty_cart_button"><span><span><?= $this->__('Clear Shopping Cart'); ?></span></span></button>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?= $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
                <?= $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
                <?php /* Extensions placeholder */ ?>
                <?= $this->getChildHtml('checkout.cart.extra') ?>
                <?= $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            </div>
        </div>
        <div class="totals overflow">
            <?= $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?= $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>
</div>
