<?php if($crumbs && is_array($crumbs)) { ?>
<ol class="breadcrumb">
    <?php foreach($crumbs as $_crumbName=>$_crumbInfo) { ?>
        <li class="<?= $_crumbName ?>">
        <?php if($_crumbInfo['link']){ ?>
            <a href="<?= $_crumbInfo['link'] ?>" title="<?= $this->escapeHtml($_crumbInfo['title']) ?>"><?= $this->escapeHtml($_crumbInfo['label']) ?></a>
        <?php } elseif($_crumbInfo['last']) { ?>
            <strong><?= $this->escapeHtml($_crumbInfo['label']) ?></strong>
        <?php } else { ?>
            <?= $this->escapeHtml($_crumbInfo['label']) ?>
        <?php } ?>
        <?php if(!$_crumbInfo['last']){ ?>
            <span>/ </span>
        <?php } ?>
        </li>
    <?php } ?>
</ol>
<?php } ?>
