<div class="row">
    <div class="col-md-4">
        <?= $this->getChildHtml('footer-company') ?>
    </div>
    <div class="col-md-8">
        <div class="row">
            <?= $this->getChildHtml('footer-cmslinks') ?>
        </div>
        <div class="row mt20">
            <div class="col-md-6">
                <?= $this->getChildHtml('footer-newsletter') ?>
            </div>
            <div class="col-md-6">
                <?= $this->getChildHtml('footer-social') ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <?= $this->getCopyright() ?>
    </div>
    <div class="col-md-4">
        <?= $this->getChildHtml('footer-cards') ?>
    </div>
</div>


