<?php

    use Del\Css;
    use Del\Icon;  

?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>" />
<title><?= $this->getTitle() ?></title>
<meta name="description" content="<?= htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?= htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?= htmlspecialchars($this->getRobots()) ?>" />
<link rel="shortcut icon" href="<?= $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?= $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?= $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?= $this->getCssJsHtml() ?>
<?= $this->getChildHtml() ?>
<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getIncludes() ?>
<?= Css::add(); ?>
<?= Icon::fontAwesomeHeadCssLink(); ?>