<?php

?>
<div class="row">
    <div class="col-md-4">
        <h2 class="mt0"><?= $this->__('Discount Codes') ?></h2>
    </div>
    <div class="col-md-8">
        <form id="discount-coupon-form" action="<?= $this->getUrl('checkout/cart/couponPost') ?>" method="post" class="overflow form-inline">
            <label for="coupon_code"><?= $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
                <input class="input-text form-control" id="coupon_code" name="coupon_code" value="<?= $this->escapeHtml($this->getCouponCode()) ?>" />
                <button type="button" title="<?= $this->__('Apply Coupon') ?>" class="button  btn btn-primary" onclick="discountForm.submit(false)" value="<?= $this->__('Apply Coupon') ?>"><span><span><?= $this->__('Apply Coupon') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?= $this->__('Cancel Coupon') ?>" class="button btn btn-primary" onclick="discountForm.submit(true)" value="<?= $this->__('Cancel Coupon') ?>"><span><span><?= $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
        </form>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
