<?php

if ($this->getIsNeedToDisplaySideBar())
{
?>
<div class="block block-cart block-topcart">
    <?php $cart_qty = $this->getSummaryCount(); ?>
    <div class="block-title">
        <div class="block-title">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <strong><span><?= $this->__('My Cart') ?></span></strong>

            <?php
            if ($cart_qty > 0) {
                $s = $cart_qty == 1 ? '' : 's';
                ?>
                <p class="amount">
                    <?= $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $cart_qty); ?>
                    <?= Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                </p>
            <?php } else { ?>
                <p class="empty"><?= $this->__('You have no items in your shopping cart.') ?></p>
            <?php } ?>

            <?php if ($cart_qty && $this->isPossibleOnepageCheckout()) { ?>
                <div class="actions">
                    <?= $this->getChildHtml('extra_actions'); ?>
                    <button type="button" title="<?= $this->__('Checkout'); ?>" class="button"
                            onclick="setLocation('<?= $this->getCheckoutUrl() ?>')">
                        <span><span><?= $this->__('Checkout') ?></span></span>
                    </button>
                </div>
            <?php } ?>

            <?php $items = $this->getRecentItems(); ?>
            <?php if (count($items)) { ?>
                <p class="block-subtitle"><?= $this->__('Recently added item(s)'); ?></p>
                <ol id="cart-sidebar" class="mini-products-list">
                    <?php foreach ($_items as $_item) { ?>
                        <?= $this->getItemHtml($_item) ?>
                    <?php } ?>
                </ol>
                <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
            <?php } ?>
        </div>
    </div>
</div>
    <?php } ?>
